### PR TITLE
Changes to Documentation

### LINKED ISSUE #58: In Read.me add git commands to pull and push the repo.

### PR DESCRIPTION
**Pull request by hnishal**
various changes in markdown files
Fixes #58

### CODE REVIEW

**Comment by Aman1440** [comment]
Hey,
The contributors at the end of the readme.md are different from the ones who really contributed i think. Please do have a look and make the changes asap.
Thanks.

**Comment by hnishal** [comment]
either we would have to manually list member or deploy a bot

**Comment by Aman1440** [comment]
if you know to make a bot than its fine if not maybe first we can delete that contributors list. and then try to make changes.

**Comment by hnishal** [comment]
@all-contributors bot add @hnishal

**Pull request merged**
