### PR TITLE
added sorting cpp algos

### PR DESCRIPTION
**Pull request by kajalmishra7**
I am a beginner to open source

### CODE REVIEW

**Comment by Aman1440** [comment]
Hey @kajalmishra7,
Thanks for your contribution. However, a few of your codes are already there in the CPP folder. you can update the files with some other codes. 

Happy Hacking.

**Comment by kajalmishra7** [comment]
Thank you Aman1440 for your prompt response.
I have updated few codes that I solved for CP contests

**Comment by Aman1440** [comment]
@kajalmishra7,

Thanks for the contribution, I have merged the pull.

**Comment by kajalmishra7** [comment]
Thank you

On Oct 1, 2020 3:03 PM, "Aman Singh" <notifications@github.com> wrote:

@kajalmishra7 <https://github.com/kajalmishra7>,

Thanks for the contribution, I have merged the pull.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Aman1440/Practice-code-repo/pull/43#issuecomment-702013801>,
or unsubscribe

**Pull request merged**
